import { Flex, Grid, GridItem } from "@chakra-ui/react";
import Head from "next/head";
import CardHand from "../../features/card/CardHand";
import { CardType, CardCategory } from "../../features/card/types/CardType";
import { InferGetServerSidePropsType } from "next";
import dbConnect from "../../lib/mongodb";
import { GameApiType, GameModel } from "../../models/GameMode";
import Deck from "../../features/deck/Deck";
import TableCard from "../../features/card/TableCard";

type ContextType = {
  params: any;
};
export async function getServerSideProps(context: ContextType) {
  const { gameId } = context.params;
  try {
    await dbConnect();
    const response = await GameModel.findById(gameId);
    return {
      props: { isConnected: true, data: JSON.stringify(response) },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { isConnected: false, data: ":(" },
    };
  }
}

const Game = ({
  isConnected,
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const gameData: GameApiType = JSON.parse(data);
  return (
    <>
      <Head>
        <title>Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid
          border="2px solid white"
          borderRadius="10px"
          w="90%"
          h="95vh"
          maxH="95vh"
          mx="auto"
          my="16px"
          p={4}
          templateRows="repeat(3, 1fr)"
        >
          <GridItem>
            <Flex align="center" justify="center" w="100%" h="100%">
              <CardHand cards={gameData.player_2_open} />
            </Flex>
          </GridItem>
          <GridItem>
            <Flex dir="row" justify="space-evenly">
              <Deck />
              <TableCard deck={gameData.on_table} />
            </Flex>
          </GridItem>
          <GridItem>
            <Flex align="center" justify="center" w="100%" h="100%">
              <CardHand cards={gameData.player_1_open} />
            </Flex>
          </GridItem>
        </Grid>
      </main>
    </>
  );
};

export default Game;
