import { Flex, Grid, GridItem } from "@chakra-ui/react";
import Head from "next/head";
import Card from "../features/card/Card";
import CardHand from "../features/card/CardHand";
import { CardType, CardCategory } from "../features/card/types/CardType";
import styles from "../styles/Home.module.css";

const testCards: CardType[] = [
  {
    value: 2,
    category: CardCategory.CLUBS,
  },
  {
    value: 5,
    category: CardCategory.DIAMONDS,
  },
  {
    value: 11,
    category: CardCategory.SPADES,
  },
  {
    value: 14,
    category: CardCategory.HEARTS,
  },
];

const Game = () => {
  return (
    <>
      <Head>
        <title>Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid
          border="2px solid white"
          borderRadius="10px"
          w="90%"
          h="95vh"
          maxH="95vh"
          mx="auto"
          my="16px"
          p={4}
          templateRows="repeat(3, 1fr)"
        >
          <GridItem>Opponent</GridItem>
          <GridItem>Deck, current played cards and graveyard</GridItem>
          <GridItem>
            <Flex align="center" justify="center" w="100%" h="100%">
              <CardHand cards={testCards} />
            </Flex>
          </GridItem>
        </Grid>
      </main>
    </>
  );
};

export default Game;
