import { Box, Button, Flex, Heading } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Card games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box w="100%">
          <Heading as="h1" size="2xl" textAlign="center" my="8px">
            Idiot!
          </Heading>
          <Flex justify="center" align="center" h="80vh">
            <Button>Create new game</Button>
          </Flex>
        </Box>
      </main>
    </>
  );
}
