import { Box, Button, Flex, Heading } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import useNewGame from "../features/games/hooks/useNewGame";

export default function Home() {
  const { data, isLoading, isSuccess, mutate } = useNewGame();
  const router = useRouter();

  useEffect(() => {
    if (isSuccess) {
      router.push("game/" + data);
    }
  }, [isSuccess, data, router]);
  return (
    <>
      <Head>
        <title>Card games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box w="100%">
          <Heading as="h1" size="2xl" textAlign="center" my="8px">
            Idiot!
          </Heading>
          <Flex justify="center" align="center" h="80vh">
            <Button onClick={() => mutate()} isLoading={isLoading}>
              Create new game
            </Button>
          </Flex>
        </Box>
      </main>
    </>
  );
}
